[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.processing]
  skip_processing = true  # Add this to skip post-processing

[build.environment]
  NODE_VERSION = "18"